### ISSUE TITLE
Missing annotation

### ISSUE THREAD

**Issue by mbuccoli** [DDMAL/salami-data-public#9]
Hello!
    I cannot find the annotations for the song 1651 (Dig It, by Beatles, from the Isophonics dataset).

**Comment by jblsmith** [comment]
As a rule, we did not annotate recordings that were shorter than 1 minute or longer than 10 minutes. (Some counterexamples are in the database because we only set this rule after a few weeks of testing, and we did not delete any work that was done.) We had the 51-second version of Dig It in our database so it was removed.
